apiVersion: eidolon/v1
kind: Agent
metadata:
  annotations: []
  labels: []
  name: query_comparer
spec:
  system_prompt: You are a helpful assistant who compares two queries that were created in response to a question.
  apu: GPT4o
  actions:
    - name: compare_queries
      user_prompt: |
        Which of the following queries is a better response to the following question?
        
        A query is considered better if it does a better job answering the provided question, would have substantially better performance.
        
        If both queries answer the provided question, perform roughly same, and are reasonably readable, consider them equal.
        
        Question: {{ question }}
        
        < query1 >
        query
        {{ query1 }}
        
        num_rows
        {{ len1 }}
        
        preview:
        {{ preview1 }}
        
        </ query1 >
        
        < query2 >
        query
        {{ query2 }}
        
        num_rows
        {{ len2 }}
        
        preview:
        {{ preview2 }}
        
        </ query2 >
      output_schema:
        type: object
        properties:
          better_query:
            type: string
            enum: [ "query1", "query2", "equal" ]
            description: Which query is better. If both are similar then equal.
