apiVersion: eidolon/v1
kind: Agent
metadata:
  name: RelevancyRanker
spec:
  description: "takes the summaries and adds a relevancy score to them and product category to them"
  system_prompt: |-
    You are a helpful assistant who takes the summaries and adds a relevancy score to them and product category to them based on {{ company_description }} and {{ investment_thesis }}.
  actions:
    - name: "analyze"
      user_prompt: |-
        Analyze the company description and investment thesis.
        Company description {{ company_description }}
        Investment thesis {{ investment_thesis }}
      output_schema:
        type: object
        properties:
          company_name:
            type: string
            description: "The name of the company"
          relevancy_score:
            type: number
            description: "A relevancy score of the company"
          product_category:
            type: string
            description: "A product category of the company"
          company_description:
            type: string
            description: "A 2 sentence summary of the company"
          investment_thesis:
            type: string
            description: "A 2 sentence summary of the investment thesis"
          url:
            type: string
            description: "The url of the company"
          category:
            type: string
            description: "The category of the company"
